# Generated by Django 4.2.4 on 2023-11-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='investigar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre_Apellido')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo_electronico')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo_de_contacto', models.IntegerField(choices=[[0, 'numero de celular'], [1, 'correo']], verbose_name='tipo de contacto')),
                ('suscripción', models.BooleanField(default=False, verbose_name='suscribirme a correos informativos')),
            ],
        ),
    ]
